require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Sem SMTP_ADDRESS: não falha a stack ao enviar; com SMTP (initializer), MAILER_RAISE_DELIVERY_ERRORS controla.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Links nos e-mails: ENV ou credentials (:mailer); fallback localhost.
  mailer_cred = (Rails.application.credentials.dig(:mailer) || {}).with_indifferent_access
  config.action_mailer.default_url_options = if ENV["MAILER_DEFAULT_URL_HOST"].present?
    {
      host: ENV.fetch("MAILER_DEFAULT_URL_HOST"),
      protocol: ENV.fetch("MAILER_DEFAULT_URL_PROTOCOL", "http"),
      port: ENV["MAILER_DEFAULT_URL_PORT"].presence&.to_i
    }.compact
  elsif mailer_cred[:default_url_host].present?
    {
      host: mailer_cred[:default_url_host],
      protocol: mailer_cred[:default_url_protocol].presence || "http",
      port: mailer_cred[:default_url_port].presence&.to_i
    }.compact
  else
    { host: "localhost", port: 3000 }
  end

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
